
[cursor]
blink_interval = 600

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"


[font.glyph_offset]
x = 0
y = 0
[font.offset]
x = 0
y = 0

# [hints.url]
# launcher = "open"
# modifiers = "None"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 20000
multiplier = 1

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[terminal.shell]
args = ["-l", "-c", "tmux"]
program = "/opt/homebrew/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = true
dynamic_title = false
opacity = 0.9
startup_mode = "Windowed"
option_as_alt = "Both"
blur = true

[window.dimensions]
columns = 100
lines = 40

[window.padding]
x = 0
y = 0

[keyboard]
bindings = [
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Plus", mods = "Control|Shift", action = "ResetFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "f", mods = "Command", action = "None" },
  { key = "I", mods = "Control", chars = "\u001b[73;5u"}
]

[general]
live_config_reload = true
import = ["/Users/distek/.config/alacritty/colors.toml"]

[terminal]
